[project]
name = "device-spinner"
version = "0.0.2"
readme = "README.md"
description = "factory pattern for object instantiation from list"
license = {text = "MIT"}
requires-python = ">=3.7"

dependencies = [
    "toml >= 0.10.2",
    "ruamel.yaml >= 0.17.35",
    "pyyaml>=6.0.1",
    "typing-extensions>=4.7.1",
    "pydantic>=2.5.3",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff>=0.9.9",
]
docs = [
    'Sphinx',
    'furo'
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = ["src", "tests"]

[tool.ruff]
line-length = 88
