devices:
    my_dict:
        module: builtins
        class: dict
        kwds:
            key0: my_val_instance
            key1: my_fixed_val
    my_val_instance:
        module: builtins
        class: str
        args:
        - val0
    my_list:
        module: builtins
        class: list
        args: [[0, 1, 2, 3]]
