name: Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    uses: AllenNeuralDynamics/.github/.github/workflows/test.yml@main
    with:
      runner_label: 'ubuntu-latest'
